version: '3.8'

services:
  frontend:
    build: .
    container_name: 'dev-finder-frontend'
    ports:
      - '4173:4173'
    environment:
      - NODE_ENV=production
    command: serve -s dist -l 4173
